sonar.projectKey=ismot-sadik-peyas_sit753-7.3hd-keycloak-api
sonar.organization=ismot-sadik-peyas
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.language=js
sonar.login=${env.SONAR_TOKEN}
